/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.19.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.demo.api;

import com.example.demo.api.model.RegisterApplianceRequest;
import com.example.demo.api.model.RegisterApplianceResponse;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-02-14T14:32:48.708622200+08:00[Asia/Shanghai]", comments = "Generator version: 7.19.0")
@Validated
public interface ApplianceApi {

    /**
     * 返回原生 Web 请求对象（用于生成代码默认逻辑）。
     *
     * @return 可选的原生请求对象
     */
    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_REGISTER_APPLIANCE = "/api/v1/appliances/register";
    /**
     * POST /api/v1/appliances/register : Register appliance instance
     *
     * @param registerApplianceRequest  (required)
     * @return Register result (status code 200)
     */
    @RequestMapping(
        method = RequestMethod.POST,
        value = ApplianceApi.PATH_REGISTER_APPLIANCE,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<RegisterApplianceResponse> registerAppliance(
         @Valid @RequestBody RegisterApplianceRequest registerApplianceRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"0\", \"data\" : { \"appliance_id\" : \"appl_8f8f7f22884f4f5fb0ea4fda5f5d6f8d\", \"is_new\" : true }, \"message\" : \"success\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
